# Generated by Django 3.2.13 on 2022-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('aswr', models.CharField(max_length=255)),
            ],
        ),
    ]
