# Generated by Django 3.2.13 on 2022-05-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220522_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='upload_date',
            new_name='upload_datetime',
        ),
    ]
