# Generated by Django 3.2.13 on 2022-06-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220601_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
    ]
