# Generated by Django 3.2.13 on 2022-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_notice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='season',
            field=models.CharField(max_length=255),
        ),
    ]
